about/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about, name='myabout'),
  
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.books, name='mybooks'),
    
  
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='myhomepage'),
  
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.loginpage, name='myloginpage'),
    path('logedin/', views.logedin, name="mylogedin"),
    path('logout/', views.log_out, name='mylogout')

]

story6/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('about/', include('about.urls')),
    path('books/', include('books.urls')),
    path('login/', include('login.urls')),
]

about/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models
from django.utils import timezone

# Create your models here
class Status(models.Model):
    status = models.CharField(max_length=300)
    tanggal = models.DateTimeField(auto_now = True)

login/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms
from . import models
import datetime

class statusForm(forms.Form):
    status = forms.CharField(
        widget= forms.Textarea(
            attrs= {
                "class" : "txt-form form-control status-form",
                "placeholder" : "Tulis status kamu disini",
                "required"  : True,
                "rows":5, 
                "cols":10,
            }
        )
    )
    
    class Meta:
        model = models.Status
        fields = [
            'status', 'tanggal',
        ]

about/views.py
from django.shortcuts import render, redirect

# Create your views here.
def about(request):
    return render(request, 'about.html')

books/views.py
from django.shortcuts import render, redirect

# Create your views here.
def books(request):
    return render(request, 'books.html')

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import statusForm
from .models import Status

# Create your views here.

#def homepage(request):
	#if request.method == 'POST':
		#formstatus = statusForm(request.POST)
		#if formstatus.is_valid():

			#status = Status(status = formstatus.data['status'])
			#status.save()
			#return redirect('homepage:myhomepage')
	#else:
		#formstatus = statusForm()

	#status_urut = Status.objects.order_by("tanggal")
	#response = {
		#'form' : formstatus,
		#'daftar_status' : status_urut,
	#}
	#return render(request, 'homepage.html', response)
	
def homepage(request):
	form = statusForm(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		stat = Status(status = form.data['status'])
		stat.save()
	iniform = statusForm()
	urutan = Status.objects.order_by('-tanggal')
	return render(request, 'homepage.html', {'form': iniform, 'daftar_status': urutan})

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def loginpage(req):
    error = "Username or Password is wrong"
    user = req.user
    if user.is_authenticated:
        return redirect('login:mylogedin')
    if req.method == 'POST':
        form = AuthenticationForm(data=req.POST)
        if form.is_valid():
            user = form.get_user()
            login(req, user)
            return redirect('login:mylogedin')
    else:
        form = AuthenticationForm()
    return render(req, 'login.html', {'form':form, 'error':error})

def logedin(req):
    return render(req, 'logedin.html')

def log_out(req):
    logout(req)
    return redirect('login:myloginpage')

about/templates/about.html
{% extends "base.html" %}

{% load static %}
{% block head_content %}
<script>
    $( function() {
        $( "#myaccordion" ).accordion({
            collapsible: true,
            active: false,
        });
    } );
</script>
{% endblock %}

{% block page_content %}

<div class="container">
<div class="div-about container-fluid">
<h2 class="heading-about"> ABOUT ME </h2>
<img src="{% static 'img/photo2-01.jpg' %}" width="250" height="250" style="border-radius: 125px;">
<p class="text-about"> Hello! I'm Michelle and I am an Information System student at University of Indonesia. I'm interested in design and technology
    especially at web development and I'm ready to send this postcard all over the world! See you soon! :D
</p>

<div id="myaccordion">
    <h3>My Activities</h3>
    <div>
        <p>
            I am currently studying and being a media bureau staff member 
                at BEM Fasilkom UI 2019 and general secretary of Pemira IKM Fasilkom UI 2019
        </p>
    </div>
    <h3 >My Organizational dan Committee Experiences</h3>
    <div >
        <p> Bedah Kampus Universitas Indonesia 18 <br>
            CGT in Action <br>
            Compfest XI <br>
            Even Graduation Ceremony of Fasilkom UI 2019 <br>
            BEM Fasilkom UI 2019 <br>
            Pemira IKM Fasilkom UI 2019
        </p>
        
    </div>
    <h3>My Achievement</h3>
    <div>
        <p>
          Participant of Olimpiade Sains Nasional (Biology) 2016-2017 Jakarta Regional
        </p>
    </div>
</div>
</div>
</div>


{% endblock %}

books/templates/books.html
{% extends "base.html" %}

{% load static %}
{% block head_content %}
{% endblock %}

{% block page_content %}
<h1> Search your book here!</h1>
<input id="search" placeholder="Title or Author">
<button id="button" type="button">Search</button>

<div class="table-responsive-md" >
    <table class="table table-bordered" id="table-books">
        <thead class="thead-dark">
        <tr>
            <th scope="col">No</th>
            <th scope="col">Title</th>
            <th scope="col">Publisher</th>
            <th scope="col">Date</th>
            <th scope="col">Image</th>
        </tr>
        </thead>
        <tbody id="results">
        
        </tbody>
    </table>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.semanticui.min.js"></script>
<script src="https://cdn.datatables.net/plug-ins/1.10.19/dataRender/ellipsis.js"></script>
<script src="{% static 'js/bookscript.js' %}"></script>



{% endblock %}

homepage/templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html data-theme="modern">
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        
        <meta charset="utf-8">
        <title>Michelle M</title>
        {% block head_content %}
        {% endblock %}
    </head>
<body>
    <header>
        <div class="border-atas">
            <img src="{% static 'img/border-01.png' %}" width="100%" height="28" >
        </div>
        <nav class="navbar navbar-expand-lg navbar-light ">
            <a class="navbar-brand" href="{% url 'homepage:myhomepage' %}">
                <img src="{% static 'img/logo-web-01.png' %}" width="28" height="28" style="margin-left: 20px;">
            </a>
            <!-- Toggler/Collapsible Button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent" >
              <ul class="navbar-nav ml-auto " >
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homepage:myhomepage' %}">Kabar</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'about:myabout' %}">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'books:mybooks' %}">Books</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login:myloginpage' %}">Login</a>
                </li>
            </div>
          </nav>
    </header>
    <div class="toggle-container">
        <input type="checkbox" id="switch" name="theme" /><label class="labelswitch" for="switch">Toggle</label>
    </div>

    <script>
        var tglButton = document.querySelector('input[name=theme]');
        
        tglButton.addEventListener('change', function(){
          if(this.checked){
              trans()
              document.documentElement.setAttribute('data-theme', 'vintage')
          } else{
              trans()
              document.documentElement.setAttribute('data-theme', 'modern')
          }
        })

        let trans = () => {
            document.documentElement.classList.add('transition');
            window.setTimeout( () => {
              document.documentElement.classList.remove('transition')
            }, 1000)
        }

      </script>
    {% block page_content %}
    {% endblock %}
</body>
</html>

homepage/templates/homepage.html
{% extends "base.html" %}

{% load static %}
{% block head_content %}
{% endblock %}
{% block page_content %}
<h1 class="heading-homepage"> Halo, Apa Kabar?</h1>

<form method="POST" class="form">
    {% csrf_token %}
    <p> Status </p>
    {{ form.status }}
    <input type="submit" name="Post" id="id-submit">
</form>


{% for i in daftar_status %}
<div class="card text-center bg-white mb-3 " style="width: 18rem;">
    <div class="card-header text-black">
        {{i.tanggal}}
    </div>
    <div class="card-body bg-white">
        <p class="card-text">{{i.status}}</p>
    </div>
</div>



{% endfor %}
{% endblock %}

login/templates/logedin.html
{% extends "base.html" %}

{% if form.errors %}
{{error}}
{% endif %}
{% if user.is_authenticated %}
    {% load static %}
    {% block head_content %}
    {% endblock %}

    {% block page_content %}
    <h1>Selamat datang, {{user}}</h1> 
    <a href="{% url 'login:mylogout' %}">
        <div class='logout'>
            Log out
        </div>
    </a>
    {% endblock %}
    {% else %}
    <h1>Please login</h1>
    <a href="{% url 'login:myloginpage' %}">
        <div class='login'>
            Log in
        </div>
    </a>
{% endif %}

login/templates/login.html
{% extends "base.html" %}

{% load static %}
{% block head_content %}
{% endblock %}

{% block page_content %}
<h1>Let's join to be a part of my website!</h1>

{% if form.errors %}
{{error}}
{% endif %}
<form method="POST" action='{% url "login:myloginpage" %}'>
    {% csrf_token %}
    <label>Username</label>
    <br>
    {{ form.username }}
    <br>
    <label>Password</label>
    <br>
    {{ form.password }}
    <br>
    <input type="submit" value="Log in" class="button">
</form>



{% endblock %}